// Generated by gencpp from file temperature_controller/sendDataStamped.msg
// DO NOT EDIT!


#ifndef TEMPERATURE_CONTROLLER_MESSAGE_SENDDATASTAMPED_H
#define TEMPERATURE_CONTROLLER_MESSAGE_SENDDATASTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace temperature_controller
{
template <class ContainerAllocator>
struct sendDataStamped_
{
  typedef sendDataStamped_<ContainerAllocator> Type;

  sendDataStamped_()
    : header()
    , temp(0.0)  {
    }
  sendDataStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , temp(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _temp_type;
  _temp_type temp;





  typedef boost::shared_ptr< ::temperature_controller::sendDataStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::temperature_controller::sendDataStamped_<ContainerAllocator> const> ConstPtr;

}; // struct sendDataStamped_

typedef ::temperature_controller::sendDataStamped_<std::allocator<void> > sendDataStamped;

typedef boost::shared_ptr< ::temperature_controller::sendDataStamped > sendDataStampedPtr;
typedef boost::shared_ptr< ::temperature_controller::sendDataStamped const> sendDataStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::temperature_controller::sendDataStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::temperature_controller::sendDataStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace temperature_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'temperature_controller': ['/root/catkin_ws/src/temperature_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::temperature_controller::sendDataStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::temperature_controller::sendDataStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::temperature_controller::sendDataStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::temperature_controller::sendDataStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::temperature_controller::sendDataStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::temperature_controller::sendDataStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::temperature_controller::sendDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6eb6a543ec2aebc9a011b375a854603";
  }

  static const char* value(const ::temperature_controller::sendDataStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6eb6a543ec2aebcULL;
  static const uint64_t static_value2 = 0x9a011b375a854603ULL;
};

template<class ContainerAllocator>
struct DataType< ::temperature_controller::sendDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "temperature_controller/sendDataStamped";
  }

  static const char* value(const ::temperature_controller::sendDataStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::temperature_controller::sendDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 temp\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::temperature_controller::sendDataStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::temperature_controller::sendDataStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sendDataStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::temperature_controller::sendDataStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::temperature_controller::sendDataStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "temp: ";
    Printer<float>::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEMPERATURE_CONTROLLER_MESSAGE_SENDDATASTAMPED_H
