// Generated by gencpp from file asr_msgs/AsrAttributedPointCloud.msg
// DO NOT EDIT!


#ifndef ASR_MSGS_MESSAGE_ASRATTRIBUTEDPOINTCLOUD_H
#define ASR_MSGS_MESSAGE_ASRATTRIBUTEDPOINTCLOUD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <asr_msgs/AsrAttributedPoint.h>

namespace asr_msgs
{
template <class ContainerAllocator>
struct AsrAttributedPointCloud_
{
  typedef AsrAttributedPointCloud_<ContainerAllocator> Type;

  AsrAttributedPointCloud_()
    : elements()  {
    }
  AsrAttributedPointCloud_(const ContainerAllocator& _alloc)
    : elements(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::asr_msgs::AsrAttributedPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::asr_msgs::AsrAttributedPoint_<ContainerAllocator> >::other >  _elements_type;
  _elements_type elements;





  typedef boost::shared_ptr< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> const> ConstPtr;

}; // struct AsrAttributedPointCloud_

typedef ::asr_msgs::AsrAttributedPointCloud_<std::allocator<void> > AsrAttributedPointCloud;

typedef boost::shared_ptr< ::asr_msgs::AsrAttributedPointCloud > AsrAttributedPointCloudPtr;
typedef boost::shared_ptr< ::asr_msgs::AsrAttributedPointCloud const> AsrAttributedPointCloudConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/root/catkin_ws/src/common_msgs-jade-devel/geometry_msgs/msg'], 'asr_msgs': ['/root/catkin_ws/src/asr_msgs-master/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5f5fc6c0891d9c31a22ae8e14d66006";
  }

  static const char* value(const ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5f5fc6c0891d9c3ULL;
  static const uint64_t static_value2 = 0x1a22ae8e14d66006ULL;
};

template<class ContainerAllocator>
struct DataType< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asr_msgs/AsrAttributedPointCloud";
  }

  static const char* value(const ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2016, Kleinert Daniel, Meissner Pascal, Yi Xie\n\
# All rights reserved.\n\
#\n\
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:\n\
#\n\
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.\n\
#\n\
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other \n\
# materials provided with the distribution.\n\
#\n\
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific # prior written permission.\n\
#\n\
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED \n\
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \n\
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR # PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\
\n\
#When used by pose_prediction: Cloud of estimates (stripped AsrObjects) of object poses for potentially different objects.\n\
AsrAttributedPoint[] elements\n\
================================================================================\n\
MSG: asr_msgs/AsrAttributedPoint\n\
# Copyright (c) 2016, Kleinert Daniel, Meissner Pascal, Yi Xie\n\
# All rights reserved.\n\
#\n\
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:\n\
#\n\
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.\n\
#\n\
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other \n\
# materials provided with the distribution.\n\
#\n\
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific # prior written permission.\n\
#\n\
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED \n\
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \n\
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR # PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\
\n\
\n\
#Output of pose_prediction: Asr object, reduced to a single pose estimate without uncertainty.\n\
geometry_msgs/Pose pose\n\
string type\n\
string identifier\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.elements);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AsrAttributedPointCloud_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asr_msgs::AsrAttributedPointCloud_<ContainerAllocator>& v)
  {
    s << indent << "elements[]" << std::endl;
    for (size_t i = 0; i < v.elements.size(); ++i)
    {
      s << indent << "  elements[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::asr_msgs::AsrAttributedPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.elements[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASR_MSGS_MESSAGE_ASRATTRIBUTEDPOINTCLOUD_H
