// Generated by gencpp from file asr_msgs/AsrViewport.msg
// DO NOT EDIT!


#ifndef ASR_MSGS_MESSAGE_ASRVIEWPORT_H
#define ASR_MSGS_MESSAGE_ASRVIEWPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace asr_msgs
{
template <class ContainerAllocator>
struct AsrViewport_
{
  typedef AsrViewport_<ContainerAllocator> Type;

  AsrViewport_()
    : pose()
    , object_type_name_list()
    , fovx(0.0)
    , fovy(0.0)
    , ncp(0.0)
    , fcp(0.0)  {
    }
  AsrViewport_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , object_type_name_list(_alloc)
    , fovx(0.0)
    , fovy(0.0)
    , ncp(0.0)
    , fcp(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _object_type_name_list_type;
  _object_type_name_list_type object_type_name_list;

   typedef float _fovx_type;
  _fovx_type fovx;

   typedef float _fovy_type;
  _fovy_type fovy;

   typedef float _ncp_type;
  _ncp_type ncp;

   typedef float _fcp_type;
  _fcp_type fcp;





  typedef boost::shared_ptr< ::asr_msgs::AsrViewport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asr_msgs::AsrViewport_<ContainerAllocator> const> ConstPtr;

}; // struct AsrViewport_

typedef ::asr_msgs::AsrViewport_<std::allocator<void> > AsrViewport;

typedef boost::shared_ptr< ::asr_msgs::AsrViewport > AsrViewportPtr;
typedef boost::shared_ptr< ::asr_msgs::AsrViewport const> AsrViewportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asr_msgs::AsrViewport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asr_msgs::AsrViewport_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/root/catkin_ws/src/common_msgs-jade-devel/geometry_msgs/msg'], 'asr_msgs': ['/root/catkin_ws/src/asr_msgs-master/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asr_msgs::AsrViewport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asr_msgs::AsrViewport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asr_msgs::AsrViewport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asr_msgs::AsrViewport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asr_msgs::AsrViewport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asr_msgs::AsrViewport_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asr_msgs::AsrViewport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3babdea0fb223c434b4147047d0da4b";
  }

  static const char* value(const ::asr_msgs::AsrViewport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3babdea0fb223c4ULL;
  static const uint64_t static_value2 = 0x34b4147047d0da4bULL;
};

template<class ContainerAllocator>
struct DataType< ::asr_msgs::AsrViewport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asr_msgs/AsrViewport";
  }

  static const char* value(const ::asr_msgs::AsrViewport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asr_msgs::AsrViewport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2016, Kleinert Daniel, Meissner Pascal, Yi Xie\n\
# All rights reserved.\n\
#\n\
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:\n\
#\n\
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.\n\
#\n\
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other \n\
# materials provided with the distribution.\n\
#\n\
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific # prior written permission.\n\
#\n\
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED \n\
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \n\
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR # PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\
\n\
#Gotten by state_machine: Camera viewport that has been searched (in reality by the robot) for a set of objects of given types.\n\
# the viewport pose\n\
geometry_msgs/Pose pose\n\
# list of object types searched in the viewport\n\
string[] object_type_name_list\n\
\n\
# Parameters of the viewport\n\
float32 fovx\n\
float32 fovy\n\
float32 ncp\n\
float32 fcp\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::asr_msgs::AsrViewport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asr_msgs::AsrViewport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.object_type_name_list);
      stream.next(m.fovx);
      stream.next(m.fovy);
      stream.next(m.ncp);
      stream.next(m.fcp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AsrViewport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asr_msgs::AsrViewport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asr_msgs::AsrViewport_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "object_type_name_list[]" << std::endl;
    for (size_t i = 0; i < v.object_type_name_list.size(); ++i)
    {
      s << indent << "  object_type_name_list[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_type_name_list[i]);
    }
    s << indent << "fovx: ";
    Printer<float>::stream(s, indent + "  ", v.fovx);
    s << indent << "fovy: ";
    Printer<float>::stream(s, indent + "  ", v.fovy);
    s << indent << "ncp: ";
    Printer<float>::stream(s, indent + "  ", v.ncp);
    s << indent << "fcp: ";
    Printer<float>::stream(s, indent + "  ", v.fcp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASR_MSGS_MESSAGE_ASRVIEWPORT_H
