// Generated by gencpp from file hand_controller/AddTrialRequest.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_ADDTRIALREQUEST_H
#define HAND_CONTROLLER_MESSAGE_ADDTRIALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_controller
{
template <class ContainerAllocator>
struct AddTrialRequest_
{
  typedef AddTrialRequest_<ContainerAllocator> Type;

  AddTrialRequest_()
    : label()
    , force_x()
    , force_y()
    , force_z()  {
    }
  AddTrialRequest_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , force_x(_alloc)
    , force_y(_alloc)
    , force_z(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _force_x_type;
  _force_x_type force_x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _force_y_type;
  _force_y_type force_y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _force_z_type;
  _force_z_type force_z;





  typedef boost::shared_ptr< ::hand_controller::AddTrialRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_controller::AddTrialRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTrialRequest_

typedef ::hand_controller::AddTrialRequest_<std::allocator<void> > AddTrialRequest;

typedef boost::shared_ptr< ::hand_controller::AddTrialRequest > AddTrialRequestPtr;
typedef boost::shared_ptr< ::hand_controller::AddTrialRequest const> AddTrialRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_controller::AddTrialRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_controller::AddTrialRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hand_controller': ['/root/catkin_ws/src/hand_controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::AddTrialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::AddTrialRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::AddTrialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::AddTrialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::AddTrialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::AddTrialRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_controller::AddTrialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dc24b7f1f2931dc1f963137493e45ae";
  }

  static const char* value(const ::hand_controller::AddTrialRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dc24b7f1f2931dcULL;
  static const uint64_t static_value2 = 0x1f963137493e45aeULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_controller::AddTrialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_controller/AddTrialRequest";
  }

  static const char* value(const ::hand_controller::AddTrialRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_controller::AddTrialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n\
float64[] force_x\n\
float64[] force_y\n\
float64[] force_z\n\
";
  }

  static const char* value(const ::hand_controller::AddTrialRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_controller::AddTrialRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.force_x);
      stream.next(m.force_y);
      stream.next(m.force_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTrialRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_controller::AddTrialRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_controller::AddTrialRequest_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "force_x[]" << std::endl;
    for (size_t i = 0; i < v.force_x.size(); ++i)
    {
      s << indent << "  force_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.force_x[i]);
    }
    s << indent << "force_y[]" << std::endl;
    for (size_t i = 0; i < v.force_y.size(); ++i)
    {
      s << indent << "  force_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.force_y[i]);
    }
    s << indent << "force_z[]" << std::endl;
    for (size_t i = 0; i < v.force_z.size(); ++i)
    {
      s << indent << "  force_z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.force_z[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_ADDTRIALREQUEST_H
