// Generated by gencpp from file hand_controller/CashMotion.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_CASHMOTION_H
#define HAND_CONTROLLER_MESSAGE_CASHMOTION_H

#include <ros/service_traits.h>


#include <hand_controller/CashMotionRequest.h>
#include <hand_controller/CashMotionResponse.h>


namespace hand_controller
{

struct CashMotion
{

typedef CashMotionRequest Request;
typedef CashMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CashMotion
} // namespace hand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_controller::CashMotion > {
  static const char* value()
  {
    return "58a33dc31f93f315437ec032733c7477";
  }

  static const char* value(const ::hand_controller::CashMotion&) { return value(); }
};

template<>
struct DataType< ::hand_controller::CashMotion > {
  static const char* value()
  {
    return "hand_controller/CashMotion";
  }

  static const char* value(const ::hand_controller::CashMotion&) { return value(); }
};


// service_traits::MD5Sum< ::hand_controller::CashMotionRequest> should match 
// service_traits::MD5Sum< ::hand_controller::CashMotion > 
template<>
struct MD5Sum< ::hand_controller::CashMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::CashMotion >::value();
  }
  static const char* value(const ::hand_controller::CashMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::CashMotionRequest> should match 
// service_traits::DataType< ::hand_controller::CashMotion > 
template<>
struct DataType< ::hand_controller::CashMotionRequest>
{
  static const char* value()
  {
    return DataType< ::hand_controller::CashMotion >::value();
  }
  static const char* value(const ::hand_controller::CashMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_controller::CashMotionResponse> should match 
// service_traits::MD5Sum< ::hand_controller::CashMotion > 
template<>
struct MD5Sum< ::hand_controller::CashMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::CashMotion >::value();
  }
  static const char* value(const ::hand_controller::CashMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::CashMotionResponse> should match 
// service_traits::DataType< ::hand_controller::CashMotion > 
template<>
struct DataType< ::hand_controller::CashMotionResponse>
{
  static const char* value()
  {
    return DataType< ::hand_controller::CashMotion >::value();
  }
  static const char* value(const ::hand_controller::CashMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_CASHMOTION_H
