// Generated by gencpp from file hand_controller/checkGraspResponse.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_CHECKGRASPRESPONSE_H
#define HAND_CONTROLLER_MESSAGE_CHECKGRASPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_controller
{
template <class ContainerAllocator>
struct checkGraspResponse_
{
  typedef checkGraspResponse_<ContainerAllocator> Type;

  checkGraspResponse_()
    : success(false)
    , single_layer(false)
    , material()  {
    }
  checkGraspResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , single_layer(false)
    , material(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _single_layer_type;
  _single_layer_type single_layer;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _material_type;
  _material_type material;





  typedef boost::shared_ptr< ::hand_controller::checkGraspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_controller::checkGraspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct checkGraspResponse_

typedef ::hand_controller::checkGraspResponse_<std::allocator<void> > checkGraspResponse;

typedef boost::shared_ptr< ::hand_controller::checkGraspResponse > checkGraspResponsePtr;
typedef boost::shared_ptr< ::hand_controller::checkGraspResponse const> checkGraspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_controller::checkGraspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_controller::checkGraspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hand_controller': ['/root/catkin_ws/src/hand_controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::checkGraspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::checkGraspResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::checkGraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::checkGraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::checkGraspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::checkGraspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_controller::checkGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a87fef5f943ec854fec992ab903ef3aa";
  }

  static const char* value(const ::hand_controller::checkGraspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa87fef5f943ec854ULL;
  static const uint64_t static_value2 = 0xfec992ab903ef3aaULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_controller::checkGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_controller/checkGraspResponse";
  }

  static const char* value(const ::hand_controller::checkGraspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_controller::checkGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
bool single_layer\n\
string material\n\
";
  }

  static const char* value(const ::hand_controller::checkGraspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_controller::checkGraspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.single_layer);
      stream.next(m.material);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct checkGraspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_controller::checkGraspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_controller::checkGraspResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "single_layer: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.single_layer);
    s << indent << "material: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.material);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_CHECKGRASPRESPONSE_H
