// Generated by gencpp from file hand_controller/ClassifyOptoforceDataRequest.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_CLASSIFYOPTOFORCEDATAREQUEST_H
#define HAND_CONTROLLER_MESSAGE_CLASSIFYOPTOFORCEDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_controller
{
template <class ContainerAllocator>
struct ClassifyOptoforceDataRequest_
{
  typedef ClassifyOptoforceDataRequest_<ContainerAllocator> Type;

  ClassifyOptoforceDataRequest_()
    : optoforcedatabuffer()  {
    }
  ClassifyOptoforceDataRequest_(const ContainerAllocator& _alloc)
    : optoforcedatabuffer(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _optoforcedatabuffer_type;
  _optoforcedatabuffer_type optoforcedatabuffer;





  typedef boost::shared_ptr< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClassifyOptoforceDataRequest_

typedef ::hand_controller::ClassifyOptoforceDataRequest_<std::allocator<void> > ClassifyOptoforceDataRequest;

typedef boost::shared_ptr< ::hand_controller::ClassifyOptoforceDataRequest > ClassifyOptoforceDataRequestPtr;
typedef boost::shared_ptr< ::hand_controller::ClassifyOptoforceDataRequest const> ClassifyOptoforceDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hand_controller': ['/root/catkin_ws/src/hand_controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9eea1360e49ad4149a83ded8678585b";
  }

  static const char* value(const ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9eea1360e49ad41ULL;
  static const uint64_t static_value2 = 0x49a83ded8678585bULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_controller/ClassifyOptoforceDataRequest";
  }

  static const char* value(const ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string optoforcedatabuffer\n\
";
  }

  static const char* value(const ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.optoforcedatabuffer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClassifyOptoforceDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_controller::ClassifyOptoforceDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "optoforcedatabuffer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.optoforcedatabuffer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_CLASSIFYOPTOFORCEDATAREQUEST_H
