// Generated by gencpp from file hand_controller/ClassifyOptoforceDataResponse.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_CLASSIFYOPTOFORCEDATARESPONSE_H
#define HAND_CONTROLLER_MESSAGE_CLASSIFYOPTOFORCEDATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_controller
{
template <class ContainerAllocator>
struct ClassifyOptoforceDataResponse_
{
  typedef ClassifyOptoforceDataResponse_<ContainerAllocator> Type;

  ClassifyOptoforceDataResponse_()
    : classifyresult()  {
    }
  ClassifyOptoforceDataResponse_(const ContainerAllocator& _alloc)
    : classifyresult(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _classifyresult_type;
  _classifyresult_type classifyresult;





  typedef boost::shared_ptr< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ClassifyOptoforceDataResponse_

typedef ::hand_controller::ClassifyOptoforceDataResponse_<std::allocator<void> > ClassifyOptoforceDataResponse;

typedef boost::shared_ptr< ::hand_controller::ClassifyOptoforceDataResponse > ClassifyOptoforceDataResponsePtr;
typedef boost::shared_ptr< ::hand_controller::ClassifyOptoforceDataResponse const> ClassifyOptoforceDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hand_controller': ['/root/catkin_ws/src/hand_controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9ea7b48fb60c63c7402790eb3833c91";
  }

  static const char* value(const ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9ea7b48fb60c63cULL;
  static const uint64_t static_value2 = 0x7402790eb3833c91ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_controller/ClassifyOptoforceDataResponse";
  }

  static const char* value(const ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string classifyresult\n\
\n\
";
  }

  static const char* value(const ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.classifyresult);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClassifyOptoforceDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_controller::ClassifyOptoforceDataResponse_<ContainerAllocator>& v)
  {
    s << indent << "classifyresult: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.classifyresult);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_CLASSIFYOPTOFORCEDATARESPONSE_H
