// Generated by gencpp from file hand_controller/ClassifyOptoforceData.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_CLASSIFYOPTOFORCEDATA_H
#define HAND_CONTROLLER_MESSAGE_CLASSIFYOPTOFORCEDATA_H

#include <ros/service_traits.h>


#include <hand_controller/ClassifyOptoforceDataRequest.h>
#include <hand_controller/ClassifyOptoforceDataResponse.h>


namespace hand_controller
{

struct ClassifyOptoforceData
{

typedef ClassifyOptoforceDataRequest Request;
typedef ClassifyOptoforceDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClassifyOptoforceData
} // namespace hand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_controller::ClassifyOptoforceData > {
  static const char* value()
  {
    return "1b074e2d253a3e64ad0835b48e4ba924";
  }

  static const char* value(const ::hand_controller::ClassifyOptoforceData&) { return value(); }
};

template<>
struct DataType< ::hand_controller::ClassifyOptoforceData > {
  static const char* value()
  {
    return "hand_controller/ClassifyOptoforceData";
  }

  static const char* value(const ::hand_controller::ClassifyOptoforceData&) { return value(); }
};


// service_traits::MD5Sum< ::hand_controller::ClassifyOptoforceDataRequest> should match 
// service_traits::MD5Sum< ::hand_controller::ClassifyOptoforceData > 
template<>
struct MD5Sum< ::hand_controller::ClassifyOptoforceDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::ClassifyOptoforceData >::value();
  }
  static const char* value(const ::hand_controller::ClassifyOptoforceDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::ClassifyOptoforceDataRequest> should match 
// service_traits::DataType< ::hand_controller::ClassifyOptoforceData > 
template<>
struct DataType< ::hand_controller::ClassifyOptoforceDataRequest>
{
  static const char* value()
  {
    return DataType< ::hand_controller::ClassifyOptoforceData >::value();
  }
  static const char* value(const ::hand_controller::ClassifyOptoforceDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_controller::ClassifyOptoforceDataResponse> should match 
// service_traits::MD5Sum< ::hand_controller::ClassifyOptoforceData > 
template<>
struct MD5Sum< ::hand_controller::ClassifyOptoforceDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::ClassifyOptoforceData >::value();
  }
  static const char* value(const ::hand_controller::ClassifyOptoforceDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::ClassifyOptoforceDataResponse> should match 
// service_traits::DataType< ::hand_controller::ClassifyOptoforceData > 
template<>
struct DataType< ::hand_controller::ClassifyOptoforceDataResponse>
{
  static const char* value()
  {
    return DataType< ::hand_controller::ClassifyOptoforceData >::value();
  }
  static const char* value(const ::hand_controller::ClassifyOptoforceDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_CLASSIFYOPTOFORCEDATA_H
