// Generated by gencpp from file hand_controller/getRecordedBufferResponse.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_GETRECORDEDBUFFERRESPONSE_H
#define HAND_CONTROLLER_MESSAGE_GETRECORDEDBUFFERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/WrenchStamped.h>

namespace hand_controller
{
template <class ContainerAllocator>
struct getRecordedBufferResponse_
{
  typedef getRecordedBufferResponse_<ContainerAllocator> Type;

  getRecordedBufferResponse_()
    : buffer()
    , x_buffer()
    , y_buffer()
    , z_buffer()  {
    }
  getRecordedBufferResponse_(const ContainerAllocator& _alloc)
    : buffer(_alloc)
    , x_buffer(_alloc)
    , y_buffer(_alloc)
    , z_buffer(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::WrenchStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::WrenchStamped_<ContainerAllocator> >::other >  _buffer_type;
  _buffer_type buffer;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_buffer_type;
  _x_buffer_type x_buffer;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_buffer_type;
  _y_buffer_type y_buffer;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _z_buffer_type;
  _z_buffer_type z_buffer;





  typedef boost::shared_ptr< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getRecordedBufferResponse_

typedef ::hand_controller::getRecordedBufferResponse_<std::allocator<void> > getRecordedBufferResponse;

typedef boost::shared_ptr< ::hand_controller::getRecordedBufferResponse > getRecordedBufferResponsePtr;
typedef boost::shared_ptr< ::hand_controller::getRecordedBufferResponse const> getRecordedBufferResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hand_controller': ['/root/catkin_ws/src/hand_controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f0d2e2dca63a66d6097c4b52389060c";
  }

  static const char* value(const ::hand_controller::getRecordedBufferResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f0d2e2dca63a66dULL;
  static const uint64_t static_value2 = 0x6097c4b52389060cULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_controller/getRecordedBufferResponse";
  }

  static const char* value(const ::hand_controller::getRecordedBufferResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/WrenchStamped[] buffer\n\
float64[] x_buffer\n\
float64[] y_buffer\n\
float64[] z_buffer\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/WrenchStamped\n\
# A wrench with reference coordinate frame and timestamp\n\
Header header\n\
Wrench wrench\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Wrench\n\
# This represents force in free space, separated into\n\
# its linear and angular parts.\n\
Vector3  force\n\
Vector3  torque\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::hand_controller::getRecordedBufferResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.buffer);
      stream.next(m.x_buffer);
      stream.next(m.y_buffer);
      stream.next(m.z_buffer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getRecordedBufferResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_controller::getRecordedBufferResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_controller::getRecordedBufferResponse_<ContainerAllocator>& v)
  {
    s << indent << "buffer[]" << std::endl;
    for (size_t i = 0; i < v.buffer.size(); ++i)
    {
      s << indent << "  buffer[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::WrenchStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.buffer[i]);
    }
    s << indent << "x_buffer[]" << std::endl;
    for (size_t i = 0; i < v.x_buffer.size(); ++i)
    {
      s << indent << "  x_buffer[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x_buffer[i]);
    }
    s << indent << "y_buffer[]" << std::endl;
    for (size_t i = 0; i < v.y_buffer.size(); ++i)
    {
      s << indent << "  y_buffer[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y_buffer[i]);
    }
    s << indent << "z_buffer[]" << std::endl;
    for (size_t i = 0; i < v.z_buffer.size(); ++i)
    {
      s << indent << "  z_buffer[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.z_buffer[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_GETRECORDEDBUFFERRESPONSE_H
