// Generated by gencpp from file hand_controller/GraspWithForceRequest.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_GRASPWITHFORCEREQUEST_H
#define HAND_CONTROLLER_MESSAGE_GRASPWITHFORCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_controller
{
template <class ContainerAllocator>
struct GraspWithForceRequest_
{
  typedef GraspWithForceRequest_<ContainerAllocator> Type;

  GraspWithForceRequest_()
    : graspforce(0)  {
    }
  GraspWithForceRequest_(const ContainerAllocator& _alloc)
    : graspforce(0)  {
  (void)_alloc;
    }



   typedef int16_t _graspforce_type;
  _graspforce_type graspforce;





  typedef boost::shared_ptr< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GraspWithForceRequest_

typedef ::hand_controller::GraspWithForceRequest_<std::allocator<void> > GraspWithForceRequest;

typedef boost::shared_ptr< ::hand_controller::GraspWithForceRequest > GraspWithForceRequestPtr;
typedef boost::shared_ptr< ::hand_controller::GraspWithForceRequest const> GraspWithForceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_controller::GraspWithForceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hand_controller': ['/root/catkin_ws/src/hand_controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b622b99eb46c5f82062546c298013a7";
  }

  static const char* value(const ::hand_controller::GraspWithForceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b622b99eb46c5f8ULL;
  static const uint64_t static_value2 = 0x2062546c298013a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_controller/GraspWithForceRequest";
  }

  static const char* value(const ::hand_controller::GraspWithForceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 graspforce\n\
";
  }

  static const char* value(const ::hand_controller::GraspWithForceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.graspforce);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspWithForceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_controller::GraspWithForceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_controller::GraspWithForceRequest_<ContainerAllocator>& v)
  {
    s << indent << "graspforce: ";
    Printer<int16_t>::stream(s, indent + "  ", v.graspforce);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_GRASPWITHFORCEREQUEST_H
