// Generated by gencpp from file hand_controller/GraspWithForce.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_GRASPWITHFORCE_H
#define HAND_CONTROLLER_MESSAGE_GRASPWITHFORCE_H

#include <ros/service_traits.h>


#include <hand_controller/GraspWithForceRequest.h>
#include <hand_controller/GraspWithForceResponse.h>


namespace hand_controller
{

struct GraspWithForce
{

typedef GraspWithForceRequest Request;
typedef GraspWithForceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GraspWithForce
} // namespace hand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_controller::GraspWithForce > {
  static const char* value()
  {
    return "6b622b99eb46c5f82062546c298013a7";
  }

  static const char* value(const ::hand_controller::GraspWithForce&) { return value(); }
};

template<>
struct DataType< ::hand_controller::GraspWithForce > {
  static const char* value()
  {
    return "hand_controller/GraspWithForce";
  }

  static const char* value(const ::hand_controller::GraspWithForce&) { return value(); }
};


// service_traits::MD5Sum< ::hand_controller::GraspWithForceRequest> should match 
// service_traits::MD5Sum< ::hand_controller::GraspWithForce > 
template<>
struct MD5Sum< ::hand_controller::GraspWithForceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::GraspWithForce >::value();
  }
  static const char* value(const ::hand_controller::GraspWithForceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::GraspWithForceRequest> should match 
// service_traits::DataType< ::hand_controller::GraspWithForce > 
template<>
struct DataType< ::hand_controller::GraspWithForceRequest>
{
  static const char* value()
  {
    return DataType< ::hand_controller::GraspWithForce >::value();
  }
  static const char* value(const ::hand_controller::GraspWithForceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_controller::GraspWithForceResponse> should match 
// service_traits::MD5Sum< ::hand_controller::GraspWithForce > 
template<>
struct MD5Sum< ::hand_controller::GraspWithForceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::GraspWithForce >::value();
  }
  static const char* value(const ::hand_controller::GraspWithForceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::GraspWithForceResponse> should match 
// service_traits::DataType< ::hand_controller::GraspWithForce > 
template<>
struct DataType< ::hand_controller::GraspWithForceResponse>
{
  static const char* value()
  {
    return DataType< ::hand_controller::GraspWithForce >::value();
  }
  static const char* value(const ::hand_controller::GraspWithForceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_GRASPWITHFORCE_H
