// Generated by gencpp from file hand_controller/MotorAngles.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_MOTORANGLES_H
#define HAND_CONTROLLER_MESSAGE_MOTORANGLES_H

#include <ros/service_traits.h>


#include <hand_controller/MotorAnglesRequest.h>
#include <hand_controller/MotorAnglesResponse.h>


namespace hand_controller
{

struct MotorAngles
{

typedef MotorAnglesRequest Request;
typedef MotorAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorAngles
} // namespace hand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_controller::MotorAngles > {
  static const char* value()
  {
    return "9582b1b82bee1f1b3579a9d96d1b0c8c";
  }

  static const char* value(const ::hand_controller::MotorAngles&) { return value(); }
};

template<>
struct DataType< ::hand_controller::MotorAngles > {
  static const char* value()
  {
    return "hand_controller/MotorAngles";
  }

  static const char* value(const ::hand_controller::MotorAngles&) { return value(); }
};


// service_traits::MD5Sum< ::hand_controller::MotorAnglesRequest> should match 
// service_traits::MD5Sum< ::hand_controller::MotorAngles > 
template<>
struct MD5Sum< ::hand_controller::MotorAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::MotorAngles >::value();
  }
  static const char* value(const ::hand_controller::MotorAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::MotorAnglesRequest> should match 
// service_traits::DataType< ::hand_controller::MotorAngles > 
template<>
struct DataType< ::hand_controller::MotorAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::hand_controller::MotorAngles >::value();
  }
  static const char* value(const ::hand_controller::MotorAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_controller::MotorAnglesResponse> should match 
// service_traits::MD5Sum< ::hand_controller::MotorAngles > 
template<>
struct MD5Sum< ::hand_controller::MotorAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::MotorAngles >::value();
  }
  static const char* value(const ::hand_controller::MotorAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::MotorAnglesResponse> should match 
// service_traits::DataType< ::hand_controller::MotorAngles > 
template<>
struct DataType< ::hand_controller::MotorAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::hand_controller::MotorAngles >::value();
  }
  static const char* value(const ::hand_controller::MotorAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_MOTORANGLES_H
