// Generated by gencpp from file hand_controller/MotorSteps.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_MOTORSTEPS_H
#define HAND_CONTROLLER_MESSAGE_MOTORSTEPS_H

#include <ros/service_traits.h>


#include <hand_controller/MotorStepsRequest.h>
#include <hand_controller/MotorStepsResponse.h>


namespace hand_controller
{

struct MotorSteps
{

typedef MotorStepsRequest Request;
typedef MotorStepsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorSteps
} // namespace hand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_controller::MotorSteps > {
  static const char* value()
  {
    return "323528af2fa6691dff3466f8e1db56ef";
  }

  static const char* value(const ::hand_controller::MotorSteps&) { return value(); }
};

template<>
struct DataType< ::hand_controller::MotorSteps > {
  static const char* value()
  {
    return "hand_controller/MotorSteps";
  }

  static const char* value(const ::hand_controller::MotorSteps&) { return value(); }
};


// service_traits::MD5Sum< ::hand_controller::MotorStepsRequest> should match 
// service_traits::MD5Sum< ::hand_controller::MotorSteps > 
template<>
struct MD5Sum< ::hand_controller::MotorStepsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::MotorSteps >::value();
  }
  static const char* value(const ::hand_controller::MotorStepsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::MotorStepsRequest> should match 
// service_traits::DataType< ::hand_controller::MotorSteps > 
template<>
struct DataType< ::hand_controller::MotorStepsRequest>
{
  static const char* value()
  {
    return DataType< ::hand_controller::MotorSteps >::value();
  }
  static const char* value(const ::hand_controller::MotorStepsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_controller::MotorStepsResponse> should match 
// service_traits::MD5Sum< ::hand_controller::MotorSteps > 
template<>
struct MD5Sum< ::hand_controller::MotorStepsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::MotorSteps >::value();
  }
  static const char* value(const ::hand_controller::MotorStepsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::MotorStepsResponse> should match 
// service_traits::DataType< ::hand_controller::MotorSteps > 
template<>
struct DataType< ::hand_controller::MotorStepsResponse>
{
  static const char* value()
  {
    return DataType< ::hand_controller::MotorSteps >::value();
  }
  static const char* value(const ::hand_controller::MotorStepsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_MOTORSTEPS_H
