// Generated by gencpp from file hand_controller/recordFromNowRequest.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_RECORDFROMNOWREQUEST_H
#define HAND_CONTROLLER_MESSAGE_RECORDFROMNOWREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_controller
{
template <class ContainerAllocator>
struct recordFromNowRequest_
{
  typedef recordFromNowRequest_<ContainerAllocator> Type;

  recordFromNowRequest_()
    : recordFromNow(false)  {
    }
  recordFromNowRequest_(const ContainerAllocator& _alloc)
    : recordFromNow(false)  {
  (void)_alloc;
    }



   typedef uint8_t _recordFromNow_type;
  _recordFromNow_type recordFromNow;





  typedef boost::shared_ptr< ::hand_controller::recordFromNowRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_controller::recordFromNowRequest_<ContainerAllocator> const> ConstPtr;

}; // struct recordFromNowRequest_

typedef ::hand_controller::recordFromNowRequest_<std::allocator<void> > recordFromNowRequest;

typedef boost::shared_ptr< ::hand_controller::recordFromNowRequest > recordFromNowRequestPtr;
typedef boost::shared_ptr< ::hand_controller::recordFromNowRequest const> recordFromNowRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_controller::recordFromNowRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_controller::recordFromNowRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hand_controller': ['/root/catkin_ws/src/hand_controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::recordFromNowRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::recordFromNowRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::recordFromNowRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::recordFromNowRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::recordFromNowRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::recordFromNowRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_controller::recordFromNowRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01362c0401bf7abe065e1e81367f201d";
  }

  static const char* value(const ::hand_controller::recordFromNowRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01362c0401bf7abeULL;
  static const uint64_t static_value2 = 0x065e1e81367f201dULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_controller::recordFromNowRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_controller/recordFromNowRequest";
  }

  static const char* value(const ::hand_controller::recordFromNowRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_controller::recordFromNowRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool recordFromNow\n\
";
  }

  static const char* value(const ::hand_controller::recordFromNowRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_controller::recordFromNowRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.recordFromNow);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct recordFromNowRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_controller::recordFromNowRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_controller::recordFromNowRequest_<ContainerAllocator>& v)
  {
    s << indent << "recordFromNow: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.recordFromNow);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_RECORDFROMNOWREQUEST_H
