// Generated by gencpp from file hand_controller/recordFromNow.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_RECORDFROMNOW_H
#define HAND_CONTROLLER_MESSAGE_RECORDFROMNOW_H

#include <ros/service_traits.h>


#include <hand_controller/recordFromNowRequest.h>
#include <hand_controller/recordFromNowResponse.h>


namespace hand_controller
{

struct recordFromNow
{

typedef recordFromNowRequest Request;
typedef recordFromNowResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct recordFromNow
} // namespace hand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_controller::recordFromNow > {
  static const char* value()
  {
    return "a7a6eb955c6d382d4e09c68b1ae9adfc";
  }

  static const char* value(const ::hand_controller::recordFromNow&) { return value(); }
};

template<>
struct DataType< ::hand_controller::recordFromNow > {
  static const char* value()
  {
    return "hand_controller/recordFromNow";
  }

  static const char* value(const ::hand_controller::recordFromNow&) { return value(); }
};


// service_traits::MD5Sum< ::hand_controller::recordFromNowRequest> should match 
// service_traits::MD5Sum< ::hand_controller::recordFromNow > 
template<>
struct MD5Sum< ::hand_controller::recordFromNowRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::recordFromNow >::value();
  }
  static const char* value(const ::hand_controller::recordFromNowRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::recordFromNowRequest> should match 
// service_traits::DataType< ::hand_controller::recordFromNow > 
template<>
struct DataType< ::hand_controller::recordFromNowRequest>
{
  static const char* value()
  {
    return DataType< ::hand_controller::recordFromNow >::value();
  }
  static const char* value(const ::hand_controller::recordFromNowRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_controller::recordFromNowResponse> should match 
// service_traits::MD5Sum< ::hand_controller::recordFromNow > 
template<>
struct MD5Sum< ::hand_controller::recordFromNowResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::recordFromNow >::value();
  }
  static const char* value(const ::hand_controller::recordFromNowResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::recordFromNowResponse> should match 
// service_traits::DataType< ::hand_controller::recordFromNow > 
template<>
struct DataType< ::hand_controller::recordFromNowResponse>
{
  static const char* value()
  {
    return DataType< ::hand_controller::recordFromNow >::value();
  }
  static const char* value(const ::hand_controller::recordFromNowResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_RECORDFROMNOW_H
