// Generated by gencpp from file hand_controller/rubbingWithForceRequest.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_RUBBINGWITHFORCEREQUEST_H
#define HAND_CONTROLLER_MESSAGE_RUBBINGWITHFORCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_controller
{
template <class ContainerAllocator>
struct rubbingWithForceRequest_
{
  typedef rubbingWithForceRequest_<ContainerAllocator> Type;

  rubbingWithForceRequest_()
    : rubbingforce(0)  {
    }
  rubbingWithForceRequest_(const ContainerAllocator& _alloc)
    : rubbingforce(0)  {
  (void)_alloc;
    }



   typedef int16_t _rubbingforce_type;
  _rubbingforce_type rubbingforce;





  typedef boost::shared_ptr< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rubbingWithForceRequest_

typedef ::hand_controller::rubbingWithForceRequest_<std::allocator<void> > rubbingWithForceRequest;

typedef boost::shared_ptr< ::hand_controller::rubbingWithForceRequest > rubbingWithForceRequestPtr;
typedef boost::shared_ptr< ::hand_controller::rubbingWithForceRequest const> rubbingWithForceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hand_controller': ['/root/catkin_ws/src/hand_controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7c598bb551ac19d777f4b6aceec6663";
  }

  static const char* value(const ::hand_controller::rubbingWithForceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7c598bb551ac19dULL;
  static const uint64_t static_value2 = 0x777f4b6aceec6663ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_controller/rubbingWithForceRequest";
  }

  static const char* value(const ::hand_controller::rubbingWithForceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 rubbingforce\n\
";
  }

  static const char* value(const ::hand_controller::rubbingWithForceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rubbingforce);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rubbingWithForceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_controller::rubbingWithForceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_controller::rubbingWithForceRequest_<ContainerAllocator>& v)
  {
    s << indent << "rubbingforce: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rubbingforce);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_RUBBINGWITHFORCEREQUEST_H
