// Generated by gencpp from file hand_controller/SetMotorSteps.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_SETMOTORSTEPS_H
#define HAND_CONTROLLER_MESSAGE_SETMOTORSTEPS_H

#include <ros/service_traits.h>


#include <hand_controller/SetMotorStepsRequest.h>
#include <hand_controller/SetMotorStepsResponse.h>


namespace hand_controller
{

struct SetMotorSteps
{

typedef SetMotorStepsRequest Request;
typedef SetMotorStepsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMotorSteps
} // namespace hand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_controller::SetMotorSteps > {
  static const char* value()
  {
    return "5df53fa0fa1b84c4a7ebce9f68720f63";
  }

  static const char* value(const ::hand_controller::SetMotorSteps&) { return value(); }
};

template<>
struct DataType< ::hand_controller::SetMotorSteps > {
  static const char* value()
  {
    return "hand_controller/SetMotorSteps";
  }

  static const char* value(const ::hand_controller::SetMotorSteps&) { return value(); }
};


// service_traits::MD5Sum< ::hand_controller::SetMotorStepsRequest> should match 
// service_traits::MD5Sum< ::hand_controller::SetMotorSteps > 
template<>
struct MD5Sum< ::hand_controller::SetMotorStepsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::SetMotorSteps >::value();
  }
  static const char* value(const ::hand_controller::SetMotorStepsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::SetMotorStepsRequest> should match 
// service_traits::DataType< ::hand_controller::SetMotorSteps > 
template<>
struct DataType< ::hand_controller::SetMotorStepsRequest>
{
  static const char* value()
  {
    return DataType< ::hand_controller::SetMotorSteps >::value();
  }
  static const char* value(const ::hand_controller::SetMotorStepsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_controller::SetMotorStepsResponse> should match 
// service_traits::MD5Sum< ::hand_controller::SetMotorSteps > 
template<>
struct MD5Sum< ::hand_controller::SetMotorStepsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::SetMotorSteps >::value();
  }
  static const char* value(const ::hand_controller::SetMotorStepsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::SetMotorStepsResponse> should match 
// service_traits::DataType< ::hand_controller::SetMotorSteps > 
template<>
struct DataType< ::hand_controller::SetMotorStepsResponse>
{
  static const char* value()
  {
    return DataType< ::hand_controller::SetMotorSteps >::value();
  }
  static const char* value(const ::hand_controller::SetMotorStepsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_SETMOTORSTEPS_H
