// Generated by gencpp from file hand_controller/SetMotorAngles.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_SETMOTORANGLES_H
#define HAND_CONTROLLER_MESSAGE_SETMOTORANGLES_H

#include <ros/service_traits.h>


#include <hand_controller/SetMotorAnglesRequest.h>
#include <hand_controller/SetMotorAnglesResponse.h>


namespace hand_controller
{

struct SetMotorAngles
{

typedef SetMotorAnglesRequest Request;
typedef SetMotorAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMotorAngles
} // namespace hand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_controller::SetMotorAngles > {
  static const char* value()
  {
    return "985fd6b2c4a26cb7c36bfac8da43b577";
  }

  static const char* value(const ::hand_controller::SetMotorAngles&) { return value(); }
};

template<>
struct DataType< ::hand_controller::SetMotorAngles > {
  static const char* value()
  {
    return "hand_controller/SetMotorAngles";
  }

  static const char* value(const ::hand_controller::SetMotorAngles&) { return value(); }
};


// service_traits::MD5Sum< ::hand_controller::SetMotorAnglesRequest> should match 
// service_traits::MD5Sum< ::hand_controller::SetMotorAngles > 
template<>
struct MD5Sum< ::hand_controller::SetMotorAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::SetMotorAngles >::value();
  }
  static const char* value(const ::hand_controller::SetMotorAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::SetMotorAnglesRequest> should match 
// service_traits::DataType< ::hand_controller::SetMotorAngles > 
template<>
struct DataType< ::hand_controller::SetMotorAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::hand_controller::SetMotorAngles >::value();
  }
  static const char* value(const ::hand_controller::SetMotorAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_controller::SetMotorAnglesResponse> should match 
// service_traits::MD5Sum< ::hand_controller::SetMotorAngles > 
template<>
struct MD5Sum< ::hand_controller::SetMotorAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::SetMotorAngles >::value();
  }
  static const char* value(const ::hand_controller::SetMotorAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::SetMotorAnglesResponse> should match 
// service_traits::DataType< ::hand_controller::SetMotorAngles > 
template<>
struct DataType< ::hand_controller::SetMotorAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::hand_controller::SetMotorAngles >::value();
  }
  static const char* value(const ::hand_controller::SetMotorAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_SETMOTORANGLES_H
