// Generated by gencpp from file hand_controller/stopRecording.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_STOPRECORDING_H
#define HAND_CONTROLLER_MESSAGE_STOPRECORDING_H

#include <ros/service_traits.h>


#include <hand_controller/stopRecordingRequest.h>
#include <hand_controller/stopRecordingResponse.h>


namespace hand_controller
{

struct stopRecording
{

typedef stopRecordingRequest Request;
typedef stopRecordingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stopRecording
} // namespace hand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_controller::stopRecording > {
  static const char* value()
  {
    return "f583eeb433b8e7ea4c20a3695d033c86";
  }

  static const char* value(const ::hand_controller::stopRecording&) { return value(); }
};

template<>
struct DataType< ::hand_controller::stopRecording > {
  static const char* value()
  {
    return "hand_controller/stopRecording";
  }

  static const char* value(const ::hand_controller::stopRecording&) { return value(); }
};


// service_traits::MD5Sum< ::hand_controller::stopRecordingRequest> should match 
// service_traits::MD5Sum< ::hand_controller::stopRecording > 
template<>
struct MD5Sum< ::hand_controller::stopRecordingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::stopRecording >::value();
  }
  static const char* value(const ::hand_controller::stopRecordingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::stopRecordingRequest> should match 
// service_traits::DataType< ::hand_controller::stopRecording > 
template<>
struct DataType< ::hand_controller::stopRecordingRequest>
{
  static const char* value()
  {
    return DataType< ::hand_controller::stopRecording >::value();
  }
  static const char* value(const ::hand_controller::stopRecordingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_controller::stopRecordingResponse> should match 
// service_traits::MD5Sum< ::hand_controller::stopRecording > 
template<>
struct MD5Sum< ::hand_controller::stopRecordingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_controller::stopRecording >::value();
  }
  static const char* value(const ::hand_controller::stopRecordingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_controller::stopRecordingResponse> should match 
// service_traits::DataType< ::hand_controller::stopRecording > 
template<>
struct DataType< ::hand_controller::stopRecordingResponse>
{
  static const char* value()
  {
    return DataType< ::hand_controller::stopRecording >::value();
  }
  static const char* value(const ::hand_controller::stopRecordingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_STOPRECORDING_H
