// Generated by gencpp from file hand_controller/stopRecordingResponse.msg
// DO NOT EDIT!


#ifndef HAND_CONTROLLER_MESSAGE_STOPRECORDINGRESPONSE_H
#define HAND_CONTROLLER_MESSAGE_STOPRECORDINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_controller
{
template <class ContainerAllocator>
struct stopRecordingResponse_
{
  typedef stopRecordingResponse_<ContainerAllocator> Type;

  stopRecordingResponse_()
    : stopRecording(false)  {
    }
  stopRecordingResponse_(const ContainerAllocator& _alloc)
    : stopRecording(false)  {
  (void)_alloc;
    }



   typedef uint8_t _stopRecording_type;
  _stopRecording_type stopRecording;





  typedef boost::shared_ptr< ::hand_controller::stopRecordingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_controller::stopRecordingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct stopRecordingResponse_

typedef ::hand_controller::stopRecordingResponse_<std::allocator<void> > stopRecordingResponse;

typedef boost::shared_ptr< ::hand_controller::stopRecordingResponse > stopRecordingResponsePtr;
typedef boost::shared_ptr< ::hand_controller::stopRecordingResponse const> stopRecordingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_controller::stopRecordingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_controller::stopRecordingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hand_controller': ['/root/catkin_ws/src/hand_controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::stopRecordingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_controller::stopRecordingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::stopRecordingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_controller::stopRecordingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::stopRecordingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_controller::stopRecordingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_controller::stopRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3b37439101b705e65e4f60a27eeaee3";
  }

  static const char* value(const ::hand_controller::stopRecordingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3b37439101b705eULL;
  static const uint64_t static_value2 = 0x65e4f60a27eeaee3ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_controller::stopRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_controller/stopRecordingResponse";
  }

  static const char* value(const ::hand_controller::stopRecordingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_controller::stopRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool stopRecording\n\
";
  }

  static const char* value(const ::hand_controller::stopRecordingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_controller::stopRecordingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stopRecording);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stopRecordingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_controller::stopRecordingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_controller::stopRecordingResponse_<ContainerAllocator>& v)
  {
    s << indent << "stopRecording: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stopRecording);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_CONTROLLER_MESSAGE_STOPRECORDINGRESPONSE_H
